language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:~/.cabal/bin:$PATH
  - ghc --version
  - cabal --version
  - cabal update
  # workaround for https://ghc.haskell.org/trac/ghc/ticket/9221
  # taken from https://github.com/hvr/multi-ghc-travis/blob/0fa68f78c2b1b059f904c9abc85510a3bb4f57e2/README.md
  - sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config

install:
  - cabal install --jobs=2 --enable-tests --only-dependencies -ftcp . distributed-process-tests/

script:
  - cabal install --jobs=2
  - cd distributed-process-tests/
  - cabal configure -ftcp --enable-tests
  - cabal build --jobs=2
  # skip intermittent tests Reconnect and SpawnReconnect
  - dist/build/TestCHInMemory/TestCHInMemory --plain -t '!Flaky'
  - dist/build/TestCHInTCP/TestCHInTCP --plain -t '!Flaky'
  - dist/build/TestClosure/TestClosure --plain -t '!SpawnReconnect'
  - dist/build/TestStats/TestStats --plain
  - dist/build/TestMx/TestMx --plain
  - dist/build/TestTracing/TestTracing --plain
